//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Microsoft Power Platform Tools")]
[assembly: AssemblyDescription("Microsoft Power Platform Tools for Visual Studio")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyProduct("Microsoft Dynamics© CRM")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0000.1")]
[assembly: AssemblyInformationalVersion("0.1.0000.1+gd485dc2")]
[assembly: AssemblyCopyright("© 2021 Microsoft Corporation. All rights reserved")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("bfc0a6ae-8414-40f4-8eed-67c324494727")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]