name: pr
on: push
env:
  SOLUTION_PATH: ./src/SelfContainedSolutionTest/code-first/SelfContainedSolutionTest
jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: git configure long path
        run: git config --global core.longpaths true
      - uses: actions/checkout@v2
      - name: base64-to-file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: SelfContainedSolutionTest.snk
          fileDir: ./src/SelfContainedSolutionTest/code-first/Plugins
          encodedString: ${{ secrets.SNK }}
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
      - name: Restore Packages
        run: |
          nuget restore ${{ env.SOLUTION_PATH }}.sln
      - name: Build Visual Studio Solution
        run: |
          msbuild.exe ${{ env.SOLUTION_PATH }}.sln /p:configuration="Release"
      - name: T Solution
        run: |
          vstest.console.exe ${{ env.SOLUTION_PATH }}/Plugins.Tests/bin/Release/SelfContainedSolutionTest.Plugins.Tests.dll

