name: pr
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: git configure long path
        run: git config --global core.longpaths true
      - uses: actions/checkout@v2
      - name: base64-to-file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: SelfContainedSolutionTest.pfx
          fileDir: ./src/SelfContainedSolutionTest/code-first/Plugins/SelfContainedSolutionTest.pfx
          encodedString: ${{ secrets.PFX }}
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
      - name: Restore Packages
        run: |
          nuget restore ./src/SelfContainedSolutionTest/code-first/SelfContainedSolutionTest.sln
      - name: Build Solution
        run: |
          msbuild.exe ./src/SelfContainedSolutionTest/code-first/SelfContainedSolutionTest.sln /p:configuration="Release"

