name: pr
on: push
env:
  SOLUTION_PATH: ./src/SelfContainedSolutionTest/code-first
jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: git configure long path
        run: git config --global core.longpaths true
      - uses: actions/checkout@v2
      - name: base64-to-file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: SelfContainedSolutionTest.snk
          fileDir: ./src/SelfContainedSolutionTest/code-first/Plugins
          encodedString: ${{ secrets.SNK }}
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
      - name: Restore Packages
        run: |
          nuget restore ${{ env.SOLUTION_PATH }}/SelfContainedSolutionTest.sln
      - name: Build Visual Studio Solution
        run: |
          msbuild.exe ${{ env.SOLUTION_PATH }}/SelfContainedSolutionTest.sln /p:configuration="Release"
      - name: Run Unit Tests
        run: |
          vstest.console.exe ${{ env.SOLUTION_PATH }}/Plugins.Tests/bin/Release/SelfContainedSolutionTest.Plugins.Tests.dll /Enablecodecoverage /Logger:trx
          mkdir reports
          Copy-Item (Get-ChildItem *.trx -Recurse)[0].FullName reports/test-report.trx
          Copy-Item (Get-ChildItem *.coverage -Recurse)[0] reports/test.coverage
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Test Results
          path: reports/test-report.trx
          reporter: dotnet-trx
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.0.3
        with:
          reports: reports/test.coverage
          targetdir: reports
          reporttypes: Cobertura
      - name: Attach Coverage Report
        uses: 5monkeys/cobertura-action@master
        with:
          path: reports/Cobertura.xml
          report_name: Code Coverage
          fail_below_threshold: true
          minimum_coverage: 100
          show_line: true
          repo_token: ${{ github.token }}


