name: pr
on: 
  pull_request:
    branches:
    - main
env:
  VS_SOLUTION_PATH: ./src/SelfContainedSolutionTest/code-first
  PP_UNPACKED_SOLUTION_PATH: ./src/SelfContainedSolutionTest/unpacked-solution
jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: git configure long path
        run: |
          git config --global core.longpaths true
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Create Plugin snk
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: SelfContainedSolutionTest.snk
          fileDir: ./src/SelfContainedSolutionTest/code-first/Plugins
          encodedString: ${{ secrets.SNK }}
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
      - name: Restore Packages
        run: |
          nuget restore ${{ env.VS_SOLUTION_PATH }}/SelfContainedSolutionTest.sln
      - name: Build Visual Studio Solution
        run: |
          msbuild.exe ${{ env.VS_SOLUTION_PATH }}/SelfContainedSolutionTest.sln /p:configuration="Release"
      - name: Run Unit Tests
        run: |
          vstest.console.exe ${{ env.VS_SOLUTION_PATH }}/Plugins.Tests/bin/Release/SelfContainedSolutionTest.Plugins.Tests.dll /Enablecodecoverage /Logger:trx
      - name: Copy Unit Test Results
        run: |
          mkdir reports
          Copy-Item (Get-ChildItem *.trx -Recurse)[0].FullName reports/test-report.trx
          Copy-Item (Get-ChildItem *.coverage -Recurse)[0] reports/test.coverage
      - name: Report Unit Test Results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Test Results
          path: reports/test-report.trx
          reporter: dotnet-trx
      - name: Convert VS .coverage to Cobertura
        uses: danielpalme/ReportGenerator-GitHub-Action@5.0.3
        with:
          reports: reports/test.coverage
          targetdir: reports
          reporttypes: Cobertura
      - name: Attach Coverage Report
        uses: 5monkeys/cobertura-action@master
        with:
          path: reports/Cobertura.xml
          report_name: Code Coverage
          fail_below_threshold: true
          minimum_coverage: 100
          show_line: true
          repo_token: ${{ github.token }}
      - name: Prepare Power Platform Solution for pack
        run: |
          # Ran into pack issues with long paths, so moving to a directory to workaround issue
          $tempUnpacked = (New-Item -Path "${{ runner.temp }}/u" -ItemType Directory).FullName
          Copy-Item "${{ env.PP_UNPACKED_SOLUTION_PATH }}/*" "$tempUnpacked" -Recurse -Force
          # need to remove the unpacked canvas code in the _msapp folder
          $msappUnpackPath = (Get-ChildItem "$tempUnpacked/CanvasApps/*_msapp")[0].FullName
          Remove-Item $msappUnpackPath -Force -Recurse
      - name: Copy Plugin dll to Power Platform Solution unpacked folder
        run: |          
          $source = "${{ env.VS_SOLUTION_PATH }}/Plugins/bin/Release/SelfContainedSolutionTest.Plugins.dll"
          $destination = "${{ runner.temp }}/u/PluginAssemblies/SelfContainedSolutionTestPlugins-BB2613D0-D86D-4460-B4EE-6042046E2ED9/SelfContainedSolutionTestPlugins.dll"
          Copy-Item $source $destination -Force
      - name: Pack Power Platform Solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: ${{ runner.temp }}/SelfContainedSolutionTest.zip
          solution-folder: ${{ runner.temp }}/u
          solution-type: Both
      - name: Import Power Platform Solution
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          solution-file: ${{ runner.temp }}/SelfContainedSolutionTest_managed.zip
          environment-url: ${{ secrets.ENVIRONMENT_URL }}
          tenant-id: ${{ secrets.TENANT_ID }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          force-overwrite: true
          use-deployment-settings-file: true
          deployment-settings-file: src/SelfContainedSolutionTest/config/deploymentSettings.json
          run-asynchronously: true